### ISSUE TITLE
FunctorMaybe

### ISSUE THREAD

**Issue by andrewthad** [ryantrinkle/reflex#19]
I feel like `FunctorMaybe` isn't the most useful typeclass. It's got one instance, and that let's us call things like `ffilter` on `Event`s. It seems like it would be better to just have functions `filterEvent` and `filterMapEvent` instead of `ffilter` and `fforMaybe`. They would be more monomorphic and more understandable.

**Comment by mightybyte** [comment]
I'm not sure of how important the type class is, but I use fmapMaybe all the time.  Removing those functions would break a lot of code.  They also feel more fundamental to me than the filter variants.

**Comment by ryantrinkle** [comment]
I would much prefer to reuse an existing typeclass with this functionality rather than creating my own - I agree that it's not terribly useful so long as it's living in this library and only used by Event.  However, I asked around and I wasn't able to find something that already existed.  I'd be happy to switch to using an external typeclass if there's one that provides this functionality.  Please feel free to reopen this issue if you have one in mind.

**Comment by bennofs** [comment]
@ryantrinkle How about http://hackage.haskell.org/package/filtrable-0.1.0.2/docs/Data-Filtrable.html ?

**Comment by andrewthad** [comment]
Yeah. That one seems like a pretty solid choice.

**Comment by andrewthad** [comment]
Also, even better than the `filterable` package is [witherable](https://hackage.haskell.org/package/witherable-0.1.3.2/docs/Data-Witherable.html)

**Comment by ryantrinkle** [comment]
Looks reasonable. @bennofs; any thoughts?

**Comment by bennofs** [comment]
@andrewthad @ryantrinkle `witherable` won't work for us, since `Event` cannot be `Traversable` (which `witherable` requires as a superclass and the `wither` function can be used to implement `traverse` I believe). The reason for that is that there is no way to get infomation "out" of an Event (think of `traverse` with the `Const` applicative).

**Comment by spl** [comment]
I also agree that the `FunctorMaybe` is a strange beast, being in `Reflex.Class` and having only one instance. But since it is useful and already there, I would prefer that it remain that way until something  decidedly better comes along.

As for `witherable`, I wonder if the `Traversable` superclass is really necessary or just a convenience. It's only used here in the class definition:

```haskell
class Traversable t => Witherable t where
  wither :: Applicative f => (a -> f (Maybe b)) -> t a -> f (t b)
  wither f = fmap catMaybes . traverse f
  [...]
```

Removing the `Traversable` superclass _still_ doesn't help the case for making `Event` as an instance of `Witherable`, but maybe some compromise could be made with the author of `witherable` to split up `Witherable` if we came up with a convincing case for it. Not sure if it's worth it, though.

**Comment by Ericson2314** [comment]
https://github.com/reflex-frp/reflex/pull/286 FunctorMaybe is finally deprecated!
