### ISSUE TITLE
Module links are broken in hackage starting from release 0.3.1

### ISSUE THREAD

**Issue by johnleuner** [ryantrinkle/reflex#33]
https://hackage.haskell.org/package/reflex-0.3.1

**Comment by spl** [comment]
Looks like this is fixed in https://hackage.haskell.org/package/reflex-0.3.2 ? The most common cause is a problem with the Hackage server. I noticed other packages uploaded around that time had the same problem. One solution is to upload one's own docs, but it's a slight hassle. It looks like @ryantrinkle did this for 0.3.2 (“Status: Docs uploaded by user”).

**Comment by johnleuner** [comment]
Fixed in

https://hackage.haskell.org/package/reflex-0.3.2

and

https://hackage.haskell.org/package/reflex-dom-0.2
